### ISSUE TITLE
How to use `num` with OCamlbuild?

### ISSUE THREAD

**Issue by liyishuai** [ocaml/num#11]
In QuickChick/QuickChick#102, I need to compile a program that uses `Big.big_int` into `.native` executables. Is OCamlbuild the right tool to use? If yes, how shall we avoid the error message?
> File "BinPos.mli", line 6, characters 13-24:
Error: Unbound module Big

**Comment by dra27** [comment]
The bug tracker’s not really the place for this. I know virtually nothing about Coq, but I don’t think this is even just an ocamlbuild question, as Coq has its own build system on top.

Does the information about `CAMLPKGS` in https://coq.inria.fr/refman/practical-tools/utilities.html relate to this? This should allow you to pass `-package num` somewhere along the line, which is what you ultimately need to happen.

**Comment by dra27** [comment]
I’m assuming that you’re using OCaml >= 4.06.0, as otherwise this error message would be surprising.

**Comment by liyishuai** [comment]
I'm currently using 4.06.1, with `num.1.1` installed via opam.
Below is a minimum example without Coq:

foo.mli:

    val test : unit
foo.ml:

    let test : unit = print_string (Big.string_of_big_int Big.one ^ "\n")
`ocamlbuild -package num foo.native` yields:
> File "foo.ml", line 1, characters 32-53:
Error: Unbound module Big

**Comment by nojb** [comment]
The module is called `Big_int`, not `Big`.

**Comment by liyishuai** [comment]
Thanks!

For Coq users: [ExtrOcamlZBigInt](https://coq.inria.fr/library/Coq.extraction.ExtrOcamlZBigInt.html) uses [Big](https://github.com/coq/coq/blob/master/plugins/extraction/big.ml) that wraps around the `Big_int` provided here.
