### ISSUE TITLE
`opam install num` fails

### ISSUE THREAD

**Issue by haansn08** [ocaml/num#24]
I am trying to install `num` using `opam`. However the build fails with following message:
```
# ocamlfind: Package num is already installed
#  - (file /home/dev/.opam/default/lib/num/META already exists)
```
<details><summary>Full output</summary>

<pre>[dev@localhost ~]$ eval $(opam env)
[dev@localhost ~]$ opam show num

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>num: information on all versions</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#3465A4"><b>name</b></font>         <b>num</b>
<font color="#3465A4"><b>all-versions</b></font> 0  1.0  1.1  1.2  1.3  1.4

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Version-specific details</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#3465A4"><b>version</b></font>       1.4
<font color="#3465A4"><b>repository</b></font>    default
<font color="#3465A4"><b>url.src:</b></font>      &quot;https://github.com/ocaml/num/archive/v1.4.tar.gz&quot;
<font color="#3465A4"><b>url.checksum:</b></font>
          &quot;md5=cda2b727e116a0b6a9c03902cc4b2415&quot;
          &quot;sha512=0cc9be8ad95704bb683b4bf6698bada1ee9a40dc05924b72adc7b969685c33eeb68ccf174cc09f6a228c48c18fe94af06f28bebc086a24973a066da620db8e6f&quot;
<font color="#3465A4"><b>homepage:</b></font>     &quot;https://github.com/ocaml/num/&quot;
<font color="#3465A4"><b>bug-reports:</b></font>  &quot;https://github.com/ocaml/num/issues&quot;
<font color="#3465A4"><b>dev-repo:</b></font>     &quot;git+https://github.com/ocaml/num.git&quot;
<font color="#3465A4"><b>authors:</b></font>      &quot;Valérie Ménissier-Morain&quot; &quot;Pierre Weis&quot; &quot;Xavier Leroy&quot;
<font color="#3465A4"><b>maintainer:</b></font>   &quot;Xavier Leroy &lt;xavier.leroy@inria.fr&gt;&quot;
<font color="#3465A4"><b>license:</b></font>      &quot;LGPL-2.1-only with OCaml-LGPL-linking-exception&quot;
<font color="#3465A4"><b>depends:</b></font>      &quot;ocaml&quot; {&gt;= &quot;4.06.0&quot;} &quot;ocamlfind&quot; {build &amp; &gt;= &quot;1.7.3&quot;}
<font color="#3465A4"><b>conflicts:</b></font>    &quot;base-num&quot;
<font color="#3465A4"><b>synopsis</b></font>      The legacy Num library for arbitrary-precision integer and rational arithmetic
[dev@localhost ~]$ opam install num
The following actions will be performed:
  <font color="#4E9A06">∗</font> install <b>ocamlfind</b> 1.9.1 [required by num]
  <font color="#4E9A06">∗</font> install <b>num</b>       1.4
===== <font color="#4E9A06">∗</font> 2 =====
Do you want to continue? [Y/n] y

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Gathering sources</b> <font color="#06989A">&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
[<font color="#4E9A06">num.1.4</font>] downloaded from cache at https://opam.ocaml.org/cache
[<font color="#4E9A06">ocamlfind.1.9.1</font>] downloaded from cache at https://opam.ocaml.org/cache

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Processing actions</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#4E9A06">∗</font> installed <b>ocamlfind</b>.1.9.1
<font color="#CC0000">[ERROR]</font> The installation of num failed at &quot;make findlib-install&quot;.

<font color="#CC0000">#===</font> <b>ERROR</b> <b>while installing num.1.4</b> <font color="#CC0000">===========================================#</font>
<font color="#C4A000">#</font> <font color="#C4A000">context</font>     2.0.6 | linux/x86_64 | ocaml-system.4.10.0 | https://opam.ocaml.org#d9074796
<font color="#C4A000">#</font> <font color="#C4A000">path</font>        ~/.opam/default/.opam-switch/build/num.1.4
<font color="#C4A000">#</font> <font color="#C4A000">command</font>     ~/.opam/opam-init/hooks/sandbox.sh install make findlib-install
<font color="#C4A000">#</font> <font color="#C4A000">exit-code</font>   2
<font color="#C4A000">#</font> <font color="#C4A000">env-file</font>    ~/.opam/log/num-24962-899ac0.env
<font color="#C4A000">#</font> <font color="#C4A000">output-file</font> ~/.opam/log/num-24962-899ac0.out
<font color="#C4A000">### output ###</font>
<font color="#C4A000"># </font>make -C src findlib-install
<font color="#C4A000"># </font>make[1]: Entering directory &apos;/home/dev/.opam/default/.opam-switch/build/num.1.4/src&apos;
<font color="#C4A000"># </font>sed -e &apos;/\^/d&apos; -e &apos;s/%%VERSION%%/1.4/g&apos; META.in &gt; META
<font color="#C4A000"># </font>ocamlfind install num META nums.cma libnums.a big_int.cmi nat.cmi num.cmi ratio.cmi arith_status.cmi big_int.mli nat.mli num.mli ratio.mli arith_status.mli big_int.cmti nat.cmti num.cmti ratio.cmti arith_status.cmti nums.cmxa nums.a int_misc.cmx nat.cmx big_int.cmx arith_flags.cmx ratio.cmx num.cmx arith_status.cmx nums.cmxs dllnums.so
<font color="#C4A000"># </font>ocamlfind: Package num is already installed
<font color="#C4A000"># </font> - (file /home/dev/.opam/default/lib/num/META already exists)
<font color="#C4A000"># </font>make[1]: *** [Makefile:101: findlib-install] Error 2
<font color="#C4A000"># </font>make[1]: Leaving directory &apos;/home/dev/.opam/default/.opam-switch/build/num.1.4/src&apos;
<font color="#C4A000"># </font>make: *** [Makefile:18: findlib-install] Error 2

<font color="#06989A">&lt;&gt;&lt;&gt;</font> <b>Error report</b> <font color="#06989A">&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;&lt;&gt;</font>
<font color="#CC0000">┌─ </font>The following actions <font color="#CC0000">failed</font>
<font color="#CC0000">│ </font><font color="#4E9A06">∗</font> install <b>num</b> 1.4
<font color="#CC0000">└─ </font>
<font color="#06989A">┌─ </font>The following changes have been performed
<font color="#06989A">│ </font><font color="#4E9A06">∗</font> install <b>ocamlfind</b> 1.9.1
<font color="#06989A">└─ </font>

The former state can be restored with:
    opam switch import &quot;/home/dev/.opam/default/.opam-switch/backup/state-20210503221339.export&quot;
</pre>
</details>

**Comment by dra27** [comment]
I expect you have the num library from your OS package manager installed?

I’m afraid that’s not at present supported by opam-repository (see https://github.com/ocaml/opam-repository/issues/14646). You can either uninstall the OS’s num library and run `opam reinstall ocamlfind` or create a switch using `ocaml-base-compiler.4.10.2` instead of `ocaml-system.4.10.0` (this will cause opam to build the compiler from sources instead of using the one installed by your system)

**Comment by dra27** [comment]
(please feel free to re-open if that diagnosis isn’t correct!)

**Comment by wiredsister** [comment]
To be honest, it may merit putting this somewhere outside of this closed issue. This exact thing happened to me and I wouldn't have found it otherwise if I hadn't thought to look here. This was a transitive dependency issue for me. Reinstalling ocamlfind fixed for my mac. Thank you.
