### ISSUE TITLE
/usr/lib/ocaml/stublibs not created

### ISSUE THREAD

**Issue by chneukirchen** [ocaml/num#3]
There is a problem installing ocaml-num into a DESTDIR where /usr/lib/ocaml/stublibs does not exist yet:
`install dllnums.so /destdir//ocaml-num-1.1//usr/lib/ocaml/stublibs` will install the dllnums.so as stublibs *file*.  You need to create the directory first.

**Comment by xavierleroy** [comment]
Your OCaml installation seems quite unusual, as the `/usr/lib/ocaml/stublibs` directory is created when OCaml itself is installed in `/usr` !
```
install dllnums.so /destdir//ocaml-num-1.1//usr/lib/ocaml/stublibs
```
The Num Makefiles do not honor `$(DESTDIR)` (purposefully).  Which packaging system is setting `$(STDLIBDIR)` (or tweaking the output of `ocamlc -where`) to such a bizarre value?

**Comment by chneukirchen** [comment]
It's our own build system, which only supports creating packages from DESTDIR, which is why we replace STDLIBDIR with DESTDIR.

(I think this will be the case for many Linux distribution, so thanks for the fix.)
