### ISSUE TITLE
Num library fails to install on Cygwin/Mingw64

### ISSUE THREAD

**Issue by martin-neuhaeusser** [ocaml/num#4]
When trying to install the Num library on Windows (Cygwin + Mingw64) with OCaml 4.06.0, the build
succeeds but installation fails. I presume this is due to the incorrect filename extension that is used for the generated DLL. The scripts somehow use the $SO variable from the core configuration files of the OCaml compiler (which is for some unknown reason set to "s.o").

As far as I can tell, the filename extension used should be "dll" in the Cygwin/Mingw64 environment.

Here is the output of make all: 
```
marneu@build ~/setup/num
$ make all
make -C src all
make[1]: Entering directory '/home/marneu/setup/num/src'
ocamlc -ccopt -DBNG_ARCH_amd64 -c bng.c
ocamlc -ccopt -DBNG_ARCH_amd64 -c nat_stubs.c
ocamlmklib -oc nums bng.o nat_stubs.o
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c int_misc.mli
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c int_misc.ml
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c nat.mli
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c nat.ml
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c big_int.mli
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c big_int.ml
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c arith_flags.mli
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c arith_flags.ml
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c ratio.mli
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c ratio.ml
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c num.mli
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c num.ml
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c arith_status.mli
ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -c arith_status.ml
ocamlmklib -o nums -oc nums -linkall int_misc.cmo nat.cmo big_int.cmo arith_flags.cmo ratio.cmo num.cmo arith_status.cmo
ocamlopt -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -O3 -c int_misc.ml
ocamlopt -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -O3 -c nat.ml
ocamlopt -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -O3 -c big_int.ml
ocamlopt -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -O3 -c arith_flags.ml
ocamlopt -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -O3 -c ratio.ml
ocamlopt -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -O3 -c num.ml
ocamlopt -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -O3 -c arith_status.ml
ocamlmklib -o nums -oc nums -linkall int_misc.cmx nat.cmx big_int.cmx arith_flags.cmx ratio.cmx num.cmx arith_status.cmx
ocamlopt -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -O3 -I . -shared -o nums.cmxs nums.cmxa
make[1]: Leaving directory '/home/marneu/setup/num/src'
make -C toplevel all
make[1]: Entering directory '/home/marneu/setup/num/toplevel'
ocamlc -I ../src -I +compiler-libs -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -c num_top_printers.mli
ocamlc -I ../src -I +compiler-libs -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -c num_top_printers.ml
ocamlc -I ../src -I +compiler-libs -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -c num_top.mli
ocamlc -I ../src -I +compiler-libs -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -c num_top.ml
ocamlc -I ../src -I +compiler-libs -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -a -o num_top.cma num_top_printers.cmo num_top.cmo
make[1]: Leaving directory '/home/marneu/setup/num/toplevel'
```

The following is the output of the make install command: 
```
marneu@build ~/setup/num
$ make install
make -C src install
make[1]: Entering directory '/home/marneu/setup/num/src'
ocamlfind install num META
Installed C:/ocamlmgw64/lib/site-lib\num\META
install -m 644 nums.cma libnums.a big_int.cmi nat.cmi num.cmi ratio.cmi arith_status.cmi big_int.mli nat.mli num.mli ratio.mli arith_status.mli big_int.cmti nat.cmti num.cmti ratio.cmti arith_status.cmti nums.cmxa nums.a big_int.cmx nat.cmx num.cmx ratio.cmx arith_status.cmx nums.cmxs C:/ocamlmgw64/lib
install dllnums.s.o C:/ocamlmgw64/lib/stublibs
install: cannot stat 'dllnums.s.o': No such file or directory
make[1]: *** [Makefile:88: install] Error 1
make[1]: Leaving directory '/home/marneu/setup/num/src'
make: *** [Makefile:14: install] Error 2
```

And here an excerpt of the contents of the /config/Makefile that was used to build OCaml 4.06.0:

```
########## Toolchain and OS dependencies

TOOLCHAIN=mingw

### Toolchain prefix
TARGET=x86_64-w64-mingw32
HOST=$(TARGET)

TOOLPREF=$(TARGET)-

CCOMPTYPE=cc
O=o
A=a
S=s
SO=s.o
EXE=.exe
EMPTY=
```

**Comment by shindere** [comment]
Hello,

Thanks a lot for the report.

I am unsure how to fix this. I see two possibilities.

1. Use the $(DLL) variable instead of the $(SO) one.
In this case this can be fixed inside the num library's build system
itself.

2. Modify the value of the SO variable in the MingW and MSVC
configuration inthe OCaml build system itself.

Any clue, @xavierleroy ?

**Comment by martin-neuhaeusser** [comment]
@shindere Using $(DLL) instead of $(SO) on Cygwin/MinGW64 is what I used to compile the Num library. This works, but I am not familiar enough with the configuration to judge whether this is the right approach.
In particular, I do not know what $(SO) is intended for on Cygwin/MinGW64.

**Comment by nojb** [comment]
@shindere I think we can safely do 1: in `otherlibs/Makefile` the stub library is referred to by `dll$(CLIBNAME)$(EXT_DLL)` so we can do the same here, using `$(EXT_DLL)` instead of `.$(SO)`.

2. is also OK to do I think (in any case `$(SO)` is unused under Windows in the OCaml build system).

**Comment by xavierleroy** [comment]
I was wrong to use `$(SO)` thinking that it would expand to `so` or to `dll` as appropriate for the OS and toolchain, just like `$(O)` expands to `o` or `obj` as appropriate.  (But then I have no idea what this `$(SO)` variable is useful for.)  Will fix shortly.

**Comment by xavierleroy** [comment]
One reason why I don't like variables such as `$(EXT_DLL)` that contain both the `.` and the suffix is that `clean` rules like the following become fragile:
```
clean:
	rm -f *.cm[ioxta] *.cmx[as] *.cmti *.$(O) *.$(A) *$(EXT_DLL)
```
If `$(EXT_DLL)` is undefined (because of a typo or some other minor mistake), all files in the current directory are removed.  While if `$(O)` is undefined (because of a similar mistake), only files ending with `.`, i.e. no files, are removed.

**Comment by xavierleroy** [comment]
Fixed by commit 06796ea.

**Comment by shindere** [comment]
Xavier Leroy (2017/12/03 01:53 -0800):
> Closed #4.

Just in case you didn't know already: if you include "Closes #4" in the
commit message GitHub will do the closing.

>

**Comment by shindere** [comment]
Xavier Leroy (2017/12/03 09:49 +0000):
> One reason why I don't like variables such as `$(EXT_DLL)` that contain both the `.` and the suffix is that `clean` rules like the following become fragile:
> ```
> clean:
> 	rm -f *.cm[ioxta] *.cmx[as] *.cmti *.$(O) *.$(A) *$(EXT_DLL)
> ```
> If `$(EXT_DLL)` is undefined (because of a typo or some other minor
> mistake), all files in the current directory are removed.  While if
> `$(O)` is undefined (because of a similar mistake), only files ending
> with `.`, i.e. no files, are removed.

Yeah I tend to agree. There is the case of $(EXE), though, which can be
either "" on Unix or ".exe" on Windows.

Then about the example of clean rule you give, I think using globs in
such rules is bad practice anyway. To me, a build system should be
explicit about what it installs, uninstalls and cleans up.

**Comment by shindere** [comment]
Xavier Leroy (2017/12/03 09:42 +0000):
> I was wrong to use `$(SO)` thinking that it would expand to `so` or to
> `dll` as appropriate for the OS and toolchain, just like `$(O)`
> expands to `o` or `obj` as appropriate.  (But then I have no idea what
> this `$(SO)` variable is useful for.)  Will fix shortly.

Were you really wrong? My understanding was rather that the definition of
the variable was wrong and if it were right what you did would have
worked, no?
