### ISSUE TITLE
Should more `cmx` files be installed?

### ISSUE THREAD

**Issue by ejgallego** [ocaml/num#9]
When compiling with flambda at high optimization settings we get:
```shell
OCAMLOPT  plugins/micromega/polynomial.ml
File "_none_", line 1:
Error (warning 58): no cmx file was found in path for module Arith_flags, and its interface was not compiled with -opaque
File "_none_", line 1:
Error (warning 58): no cmx file was found in path for module Int_misc, and its interface was not compiled with -opaque
Makefile.build:736: recipe for target 'plugins/micromega/polynomial.cmx' failed
```

should the `cmx` for these files also installed?

**Comment by nojb** [comment]
Indeed, this was supposed to have been fixed (#1). Instead of installing *all* `.cmx` files, only those corresponding to modules whose `.cmi` file are installed are being installed, thus missing some (those whose `.cmi` are not installed).

**Comment by nojb** [comment]
See #10.

**Comment by ejgallego** [comment]
Thanks!

**Comment by xavierleroy** [comment]
Thanks @ejgallego for the report and @nojb for the fix.
